pipelines:
    default:
        - step:
            name: Test
            image: python:3.8-buster
            caches:
                - poetry
            script:
                - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
                - source $HOME/.poetry/env
                - poetry install
                - ./qa.sh
            artifacts:
                - test-reports/**
definitions:
  caches:
    poetry: ~/.cache/pypoetry
